/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SignUp;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Role.Role;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Validate;

/**
 *
 * @author srivaishnaviaekkati 
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpPanel
     */
    JPanel Component;
    EcoSystem sys;
    String email;
    public SignUpJPanel(JPanel Component,EcoSystem sys,String email ) {
        initComponents();
        this.Component=Component;
        this.sys=sys;
               this.email=email;  
        PopNetworkCombo();
        emailtextfield.setText(email);
        
    }
         
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void PopNetworkCombo()
           
    { 
        
        
        if(sys.getNetworkList().size()>0)
    {
        
          combonetwork.removeAllItems();
       for(Network net: sys.getNetworkList())
       {
             
           combonetwork.addItem(net); 
       
       
       }
       comboenterprise.setEnabled(true);
        
       
    }
    else 
    {
            
        JOptionPane.showMessageDialog(null,"No network available ");
       
     }
    }
    
     public void PopEnterpriseCombo(Network network)
    {        
       comboenterprise.removeAllItems();
             //Network network = (Network) combonetwork.getSelectedItem();
         
           if(network.getEnterpriseDirectory().getEnterpriseList().size()>0)
           {
               
               
                for(Enterprise en: network.getEnterpriseDirectory().getEnterpriseList())
                {
                     comboenterprise.addItem(en);
                }
  
          
           }
           
           else
           {
                combo_organization.setEnabled(false);
                comborole.setEnabled(false);
                JOptionPane.showMessageDialog(null,"Sorry !No enterprise available for this network");
           
               
           }
    }
     
       
  public void PopOrganizationCombo(Enterprise ent)
    { 
        
         combo_organization.removeAllItems();
        
          combo_organization.setEnabled(true);
                  
             if (ent.getOrganizationDirectory().getOrganizationList().size() > 0) {
                for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                    combo_organization.addItem(organization);
                }
            }
             else
             {
             
                  comborole.setEnabled(false);
                 JOptionPane.showMessageDialog(null,"Sorry !No organization available for this network");
             
             }
           
    
    }
    
     public void PopRoleCombo(Organization org)
    { 
        
            comborole.removeAllItems();
             comborole.setEnabled(true);
     
             
                  
             if (org.getSupportedRole().size()>0) {
                for (Role role : org.getSupportedRole()) {
                    comborole.addItem(role);
                }
            }
           
    
    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        emailtextfield = new javax.swing.JTextField();
        combonetwork = new javax.swing.JComboBox();
        comboenterprise = new javax.swing.JComboBox();
        combo_organization = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        usernametxtfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordtxtfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emptxtfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comborole = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(76, 89, 115));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up Form");
        add(jLabel1);
        jLabel1.setBounds(278, 88, 144, 30);

        jLabel2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Network");
        add(jLabel2);
        jLabel2.setBounds(64, 229, 53, 18);

        jLabel3.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enterprise");
        add(jLabel3);
        jLabel3.setBounds(57, 270, 60, 18);

        jLabel4.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Organization");
        add(jLabel4);
        jLabel4.setBounds(36, 311, 81, 18);

        jLabel5.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email ID");
        add(jLabel5);
        jLabel5.setBounds(400, 271, 53, 18);

        signupbtn.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        signupbtn.setText("Sign Up");
        signupbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        add(signupbtn);
        signupbtn.setBounds(342, 491, 95, 22);

        emailtextfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        emailtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtextfieldActionPerformed(evt);
            }
        });
        add(emailtextfield);
        emailtextfield.setBounds(459, 268, 152, 24);

        combonetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combonetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combonetworkActionPerformed(evt);
            }
        });
        add(combonetwork);
        combonetwork.setBounds(162, 226, 151, 23);

        comboenterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboenterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboenterpriseActionPerformed(evt);
            }
        });
        add(comboenterprise);
        comboenterprise.setBounds(162, 267, 151, 23);

        combo_organization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_organization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_organizationActionPerformed(evt);
            }
        });
        add(combo_organization);
        combo_organization.setBounds(162, 308, 151, 23);

        jLabel6.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UserName");
        add(jLabel6);
        jLabel6.setBounds(388, 309, 65, 18);

        usernametxtfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        add(usernametxtfield);
        usernametxtfield.setBounds(459, 306, 152, 24);

        jLabel7.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        add(jLabel7);
        jLabel7.setBounds(396, 354, 57, 18);

        passwordtxtfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        add(passwordtxtfield);
        passwordtxtfield.setBounds(459, 348, 152, 24);

        jLabel8.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        add(jLabel8);
        jLabel8.setBounds(416, 231, 37, 18);

        emptxtfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        add(emptxtfield);
        emptxtfield.setBounds(459, 228, 152, 24);

        jLabel9.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Role");
        add(jLabel9);
        jLabel9.setBounds(89, 352, 28, 18);

        comborole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comborole);
        comborole.setBounds(162, 349, 151, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/srivaishnaviaekkati/Downloads/AED_Project_Fall_22 2/back.png")); // NOI18N
        jLabel10.setToolTipText("");
        add(jLabel10);
        jLabel10.setBounds(0, 0, 750, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_organizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_organizationActionPerformed
        // TODO add your handling code here:
         Organization org = (Organization) combo_organization.getSelectedItem();
        if (org != null){
            PopRoleCombo(org);
         
        }
        
    }//GEN-LAST:event_combo_organizationActionPerformed

    private void emailtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtextfieldActionPerformed

    private void combonetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combonetworkActionPerformed
        // TODO add your handling code here:
    Network network = (Network) combonetwork.getSelectedItem();
        if (network != null){
            PopEnterpriseCombo(network);
      
        }
            
            
        
        
    }//GEN-LAST:event_combonetworkActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        
        Network network = (Network) combonetwork.getSelectedItem();
        Enterprise enterprise = (Enterprise) comboenterprise.getSelectedItem();
        Organization organization = (Organization)combo_organization.getSelectedItem();
        Role role = (Role) comborole.getSelectedItem();
        
        for(Network net : sys.getNetworkList() )
        {
            if(net.equals(network))
            {
                for(Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList())
                {
                    if(ent.equals(enterprise))
                    {
                         for(Organization org: ent.getOrganizationDirectory().getOrganizationList())
                         {
                                  
                             if(org.equals(organization))
                             { 
                                 if(emptxtfield.getText()!=null)
                                 { Employee emp= new Employee();
                                    emp.setName(emptxtfield.getText());
                                  
                                 if(emailtextfield.getText()!=null)
                                 {
                                        if(Validate.validateEmail(emailtextfield.getText()))
                                        {
                                             if(usernametxtfield.getText()!=null)
                                             {  
                                                 if(!EcoSystem.checkIfUsernameIsUnique(usernametxtfield.getText(),net))
                                                 {
                                                     
                                                     JOptionPane.showMessageDialog(null, usernametxtfield.getText() + " " + "is already taken please enter new username");
                                                     return;
                                                 }
                                                   if(passwordtxtfield.getText()!=null)
                                                   {
                                                       if (!Validate.validatePassword(passwordtxtfield.getText())) {
                                JOptionPane.showMessageDialog(null, "Password should Contain \n"
                                        + "       - At least one digit\n"
                                        + "       - At least one lower case letter\n"
                                        + "       - At least one upper case letter\n"
                                        + "       - At least one special character(!@#$%^&+=~|?)\n"
                                        + "       - no whitespace allowed in the entire string\n"
                                        + "       - at least eight characters");
                                passwordtxtfield.setText("");
                                return;
                            }organization.getUserAccountDirectory().createUserAccount(usernametxtfield.getText(), passwordtxtfield.getText(),emailtextfield.getText() ,emp, role);
                                                                   JOptionPane.showMessageDialog(null, "Account created succesfull");
                                                                     usernametxtfield.setText("");
                                                                        passwordtxtfield.setText("");
                                                                        emailtextfield.setText("");
                                                                        emptxtfield.setText("");
                                                                        
                                                                        
                                                        
                                                        
                                                   }
                                                   else
                                                   {
                                                      JOptionPane.showMessageDialog(null,"Please enter password");
                                                   
                                                   }
                                             }
                                             
                                             else
                                             {
                                                
                                                 JOptionPane.showMessageDialog(null,"Please enter username");
                                             
                                             }
                                        
                                        }
                                     else
                                        {
                                             JOptionPane.showMessageDialog(null,"Please enter valid email id");
                                        }
                                 }
                                 else
                                 {
                                      
                                     JOptionPane.showMessageDialog(null,"Please enter name");
                                     
                                 }
                                 }
                                 else
                                 {
                                      JOptionPane.showMessageDialog(null,"Please enter email id");
                                 }
                                      
                             
                             }
                         
                         }
                         
                    }
                
                
                }
               
            }
        
        
        }
        
        
        
        
    }//GEN-LAST:event_signupbtnActionPerformed

    private void comboenterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboenterpriseActionPerformed
        // TODO add your handling code here:
        Enterprise  ent = (Enterprise) comboenterprise.getSelectedItem();
        if (ent != null){
            PopOrganizationCombo(ent);
            
        }
       
    }//GEN-LAST:event_comboenterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_organization;
    private javax.swing.JComboBox comboenterprise;
    private javax.swing.JComboBox combonetwork;
    private javax.swing.JComboBox comborole;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JTextField emptxtfield;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passwordtxtfield;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField usernametxtfield;
    // End of variables declaration//GEN-END:variables
}
