/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ResidentialHall.AdminRole;

import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srivaishnaviaekkati
 */
public class ResidentialHallManageEmployeeJPanel extends javax.swing.JPanel {

    public String message1 = null; 
    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ResidentialHallManageEmployeeJPanel(JPanel userProcessContainer,OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        
       // populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }
    
    
    
    public void populateOrganizationEmpComboBox(){
        organizationEmpJCB.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            organizationEmpJCB.addItem(organization);
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) organizationJT.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[1];
          
            row[0] = employee.getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJT = new javax.swing.JTable();
        addJBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameJTF = new javax.swing.JTextField();
        organizationEmpJCB = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLResHallEnterPanel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(76, 89, 115));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setLayout(null);

        organizationJT.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        organizationJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJT);
        if (organizationJT.getColumnModel().getColumnCount() > 0) {
            organizationJT.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 110, 640, 160);

        addJBtn.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        addJBtn.setText("Create Employee");
        addJBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBtnActionPerformed(evt);
            }
        });
        add(addJBtn);
        addJBtn.setBounds(490, 500, 107, 22);

        backJBtn.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        backJBtn.setText("<< Back");
        backJBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });
        add(backJBtn);
        backJBtn.setBounds(180, 500, 54, 22);

        jLabel2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(230, 380, 60, 18);

        nameJTF.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        nameJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTFActionPerformed(evt);
            }
        });
        add(nameJTF);
        nameJTF.setBounds(330, 380, 190, 24);

        organizationEmpJCB.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        organizationEmpJCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationEmpJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmpJCBActionPerformed(evt);
            }
        });
        add(organizationEmpJCB);
        organizationEmpJCB.setBounds(330, 320, 190, 24);

        jLabel3.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Organization");
        add(jLabel3);
        jLabel3.setBounds(197, 320, 100, 18);

        jLResHallEnterPanel.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLResHallEnterPanel.setForeground(new java.awt.Color(255, 255, 255));
        jLResHallEnterPanel.setText("Residential Hall Enterprise Panel");
        add(jLResHallEnterPanel);
        jLResHallEnterPanel.setBounds(180, 60, 360, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void addJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBtnActionPerformed
        
        Organization organization = (Organization) organizationEmpJCB.getSelectedItem();
    //    String name = nameJTextField.getText();
       // String name = message1;
        if(nameJTF.getText().isEmpty())
        {
            
            System.out.println("Inside else block of addJButtonActionPerformed method ... ");
            JOptionPane.showMessageDialog(null," Enter the Organisation Name ");
        }
        else 
        {
            
            System.out.println("Inside if block of addJButtonActionPerformed method ... ");
            organization.getEmployeeDirectory().createEmployee(nameJTF.getText());
            populateTable(organization);
            nameJTF.setText("");
            JOptionPane.showMessageDialog(null,"Employee Created");
        }
    }//GEN-LAST:event_addJBtnActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void organizationEmpJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmpJCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationEmpJCBActionPerformed

    private void nameJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTFActionPerformed
        // TODO add your handling code here:
        
        if(nameJTF.getText()!="")
     {
        message1 = nameJTF.getText();
        System.out.println("nameJTextFieldActionPerformed 'messageJTextField' " + message1);
     }
        else JOptionPane.showMessageDialog(null,"Name field is empty!!");
        
        
    }//GEN-LAST:event_nameJTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJBtn;
    private javax.swing.JButton backJBtn;
    private javax.swing.JLabel jLResHallEnterPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTF;
    private javax.swing.JComboBox organizationEmpJCB;
    private javax.swing.JTable organizationJT;
    // End of variables declaration//GEN-END:variables
}
