/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Maintenance.Miscellaneous;

import userinterface.Maintenance.Miscellaneous.*;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FelonyOrganization;
import Business.Organization.MisconductOrganization;
import Business.Organization.Organization;
import Business.Organization.TheftOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author srivaishnaviaekkati
 */
public class MiscellaneousEmergencyRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DinerEmergencyRequestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount; 
    private Network network;
    public MiscellaneousEmergencyRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise,Network network) {
        initComponents();
        this.network=network;
       this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
     populateComboBox();
    }
EmergencyRequest  erequest = new EmergencyRequest();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        locationlbl = new javax.swing.JLabel();
        locationtxtfield23456 = new javax.swing.JTextField();
        sendemergecy56567 = new javax.swing.JButton();
        combob = new javax.swing.JComboBox();
        backJButton8900 = new javax.swing.JButton();
        hj657hvjgvj = new javax.swing.JLabel();

        setBackground(new java.awt.Color(76, 89, 115));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Emergency Type");
        add(jLabel1);
        jLabel1.setBounds(191, 210, 110, 30);

        locationlbl.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        locationlbl.setForeground(new java.awt.Color(255, 255, 255));
        locationlbl.setText("Location");
        add(locationlbl);
        locationlbl.setBounds(233, 277, 70, 30);

        locationtxtfield23456.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        add(locationtxtfield23456);
        locationtxtfield23456.setBounds(330, 280, 114, 24);

        sendemergecy56567.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        sendemergecy56567.setText("Send Emergency");
        sendemergecy56567.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendemergecy56567.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendemergecy56567ActionPerformed(evt);
            }
        });
        add(sendemergecy56567);
        sendemergecy56567.setBounds(520, 473, 110, 30);

        combob.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        combob.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(combob);
        combob.setBounds(330, 210, 114, 24);

        backJButton8900.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        backJButton8900.setText("Back");
        backJButton8900.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton8900.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton8900ActionPerformed(evt);
            }
        });
        add(backJButton8900);
        backJButton8900.setBounds(104, 470, 60, 20);

        hj657hvjgvj.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        hj657hvjgvj.setForeground(new java.awt.Color(255, 255, 255));
        hj657hvjgvj.setText("Miscellaneous Emergency Request");
        add(hj657hvjgvj);
        hj657hvjgvj.setBounds(176, 60, 360, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void sendemergecy56567ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendemergecy56567ActionPerformed
        // TODO add your handling code here:
        
         String location = locationtxtfield23456.getText();
        erequest.setLocation(location);
        erequest.setEmergencytype((Organization.Type) combob.getSelectedItem());
        erequest.setEmail(userAccount.getEmail());
         Organization org = null;
         Organization.Type sel = (Organization.Type) combob.getSelectedItem();
      if(location.isEmpty())
      {
        System.out.println("Inside else block of sendComplaintActionPerformed ");
            JOptionPane.showMessageDialog(null,"Location field is empty");     
    }
        
        else
        {
            
            
            if(sel.equals(Organization.Type.Theft))
        {   
        for (Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
            {
                  for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
                  {
            if (organization instanceof TheftOrganization){
                org = organization;
                break;
            } 
                  }
        }
        if (org!=null){
            org.getStatusQueue().getStatusRequestList().add(erequest);
            userAccount.getStatusQueue().getStatusRequestList().add(erequest);
        }
        }
          else if(sel.equals(Organization.Type.Felony))
        {
        
        for (Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
            {
                  for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
                  {
            if (organization instanceof FelonyOrganization){
                org = organization;
                break;
            } }
        }
        if (org!=null){
            org.getStatusQueue().getStatusRequestList().add(erequest);
            userAccount.getStatusQueue().getStatusRequestList().add(erequest);
        }
        }
        
          else if(sel.equals(Organization.Type.Misconduct))
        {
        
        for (Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
            {
                  for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
                  {
            if (organization instanceof MisconductOrganization){
                org = organization;
                break;
            } 
            }
        }
        if (org!=null){
            org.getStatusQueue().getStatusRequestList().add(erequest);
            userAccount.getStatusQueue().getStatusRequestList().add(erequest);
        }
        }
        
          JOptionPane.showMessageDialog(null,"Your emergency request has been sent! An officer will notify you shortly");
        
        }
    }//GEN-LAST:event_sendemergecy56567ActionPerformed

    private void backJButton8900ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton8900ActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MiscellaneousWorkAreaJPanel fwajp = (MiscellaneousWorkAreaJPanel) component;
        
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton8900ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton8900;
    private javax.swing.JComboBox combob;
    private javax.swing.JLabel hj657hvjgvj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel locationlbl;
    private javax.swing.JTextField locationtxtfield23456;
    private javax.swing.JButton sendemergecy56567;
    // End of variables declaration//GEN-END:variables

    private void populateComboBox() {
         combob.removeAllItems();
        combob.addItem(Organization.Type.Theft);
        combob.addItem(Organization.Type.Felony);
        combob.addItem(Organization.Type.Misconduct);
    }
}
