/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SignUp;

import Business.EcoSystem;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.Police.felony.FelonyWorkAreaJPanel;
 import utility.Validate;
//import utility.Mail;
import utility.ValidateMail;
/**
 *
 * @author srivaishnaviaekkati
 */
public class AuthenticationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthenticationJPanel
     */
    Random rand = new Random();

int n = rand.nextInt(10000);
JPanel container;
    EcoSystem sys;
    public AuthenticationJPanel(JPanel container,EcoSystem sys ) {
        initComponents();
        this.container=container;
        this.sys=sys;
         plzEnterjLabel2.setVisible(false);
            authCodetxtfield.setVisible(false);
            authenticationtxtfield.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterEmailText = new javax.swing.JLabel();
        txtEmailfield = new javax.swing.JTextField();
        authCodetxtfield = new javax.swing.JTextField();
        sendEmailjButton1 = new javax.swing.JButton();
        plzEnterjLabel2 = new javax.swing.JLabel();
        authenticationtxtfield = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(76, 89, 115));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setPreferredSize(new java.awt.Dimension(750, 750));
        setLayout(null);

        enterEmailText.setFont(new java.awt.Font("Optima", 0, 18)); // NOI18N
        enterEmailText.setForeground(new java.awt.Color(255, 255, 255));
        enterEmailText.setText("Enter your email id for the verification ");
        add(enterEmailText);
        enterEmailText.setBounds(200, 100, 320, 23);

        txtEmailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailfieldActionPerformed(evt);
            }
        });
        add(txtEmailfield);
        txtEmailfield.setBounds(240, 130, 238, 23);

        authCodetxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authCodetxtfieldActionPerformed(evt);
            }
        });
        add(authCodetxtfield);
        authCodetxtfield.setBounds(310, 360, 101, 23);

        sendEmailjButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sendEmailjButton1.setText("Send Mail");
        sendEmailjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailjButton1ActionPerformed(evt);
            }
        });
        add(sendEmailjButton1);
        sendEmailjButton1.setBounds(320, 200, 92, 23);

        plzEnterjLabel2.setFont(new java.awt.Font("Optima", 0, 18)); // NOI18N
        plzEnterjLabel2.setForeground(new java.awt.Color(255, 255, 255));
        plzEnterjLabel2.setText("Please enter the four digit code that has been sent to your email entered above");
        add(plzEnterjLabel2);
        plzEnterjLabel2.setBounds(70, 310, 607, 23);

        authenticationtxtfield.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        authenticationtxtfield.setText("Authenticate");
        authenticationtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticationtxtfieldActionPerformed(evt);
            }
        });
        add(authenticationtxtfield);
        authenticationtxtfield.setBounds(300, 420, 129, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/srivaishnaviaekkati/Downloads/AED_Project_Fall_22 2/back.png")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void sendEmailjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailjButton1ActionPerformed
        // TODO add your handling code here:
    //     JOptionPane.showMessageDialog(emailtxtfield, n);
    //    JOptionPane.showMessageDialog(this, 56789);
    //    authtxtfield.setVisible(true);
        
//        jLabel2.setVisible(true);
//            authtxtfield.setVisible(true);
//            authenticatetxtfield.setVisible(true);
            String email = null;
        if(txtEmailfield.getText()!=null)
            {
                if(Validate.validateEmail(txtEmailfield.getText()))
                {
                    email = txtEmailfield.getText();
                    System.out.println("email .. "+ email);
                    System.out.println("After If Statement .. ");
                    
                

         try {
             ValidateMail valMail = new ValidateMail();
             try {
                 //Validate.sendMessage1(emailtxtfield.getText(),n);
             //    valMail.preparetoSendEmail("This is Subject", "This is Verification code : " + n, emailtxtfield.getText());
             System.out.println("Inside If Statement .. ");
             valMail.preparetoSendEmail("This is Subject", "This is Verification code : " + n, email);

             } catch (AddressException ex) {
                 Logger.getLogger(AuthenticationJPanel.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(AuthenticationJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }
              
            JOptionPane.showMessageDialog(this,"Mail has been sent");
            plzEnterjLabel2.setVisible(true);
            authCodetxtfield.setVisible(true);
            authenticationtxtfield.setVisible(true);
        } catch (MessagingException ex) {
            Logger.getLogger(FelonyWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Mail has not  been sent");
        }
         
                }     
                
            else {
            JOptionPane.showMessageDialog(null,"Please enter valid email id");
             System.out.println("Inside else Statement .. ");
            }
         
        }
        else {
            JOptionPane.showMessageDialog(null,"Please enter email id");
             System.out.println("Inside else Statement .. ");
            }

         
    }//GEN-LAST:event_sendEmailjButton1ActionPerformed

    private void authenticationtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticationtxtfieldActionPerformed
        // TODO add your handling code here:
    //    Integer num=Integer.parseInt(authtxtfield.getText());
        Integer num = n; 
    
    
        if(num.equals(n))
        {
        
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("SignUpJPanel", new SignUpJPanel(container, sys,txtEmailfield.getText()));
        layout.next(container);
        
        }
        else
        {
        
          JOptionPane.showMessageDialog(null,"Authentication failed");
        
        }
    }//GEN-LAST:event_authenticationtxtfieldActionPerformed

    private void authCodetxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authCodetxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authCodetxtfieldActionPerformed

    private void txtEmailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authCodetxtfield;
    private javax.swing.JButton authenticationtxtfield;
    private javax.swing.JLabel enterEmailText;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel plzEnterjLabel2;
    private javax.swing.JButton sendEmailjButton1;
    private javax.swing.JTextField txtEmailfield;
    // End of variables declaration//GEN-END:variables
}
