

package userinterface.ResidentialHall.AdminRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  srivaishnaviaekkati
 */
public class ResidentialHallAdminWorkAreaJPanel extends javax.swing.JPanel {
     
    JPanel userProcessContainer;
    Network network;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public ResidentialHallAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,Network network) {
        initComponents();
        this.network=network;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLbl.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userbtn = new javax.swing.JButton();
        manageEmployebtn = new javax.swing.JButton();
        manageOrganizationbtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(76, 89, 115));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Residential Hall Enterprise Panel");
        add(jLabel1);
        jLabel1.setBounds(210, 100, 360, 30);

        userbtn.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        userbtn.setText("Manage User");
        userbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });
        add(userbtn);
        userbtn.setBounds(500, 350, 150, 60);

        manageEmployebtn.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        manageEmployebtn.setText("Manage Employee");
        manageEmployebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageEmployebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployebtnActionPerformed(evt);
            }
        });
        add(manageEmployebtn);
        manageEmployebtn.setBounds(290, 350, 150, 60);

        manageOrganizationbtn.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        manageOrganizationbtn.setText("Manage Organization");
        manageOrganizationbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageOrganizationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationbtnActionPerformed(evt);
            }
        });
        add(manageOrganizationbtn);
        manageOrganizationbtn.setBounds(70, 350, 137, 60);

        enterpriseLabel.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(220, 200, 120, 40);

        valueLbl.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        valueLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(valueLbl);
        valueLbl.setBounds(320, 207, 170, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        // TODO add your handling code here:
        ResidentialHallManageUserAccountJPanel muajp = new ResidentialHallManageUserAccountJPanel(userProcessContainer, enterprise,network);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userbtnActionPerformed

    private void manageEmployebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployebtnActionPerformed

        ResidentialHallManageEmployeeJPanel manageEmployeeJPanel = new ResidentialHallManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployebtnActionPerformed

    private void manageOrganizationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationbtnActionPerformed

        ResidentialHallManageOrganizationJPanel manageOrganizationJPanel = new ResidentialHallManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationbtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployebtn;
    private javax.swing.JButton manageOrganizationbtn;
    private javax.swing.JButton userbtn;
    private javax.swing.JLabel valueLbl;
    // End of variables declaration//GEN-END:variables
    
}
