

package userinterface.Maintenance.Admin;

import userinterface.Maintenance.Admin.*;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  srivaishnaviaekkati
 */
public class MaintenanceAdminWorkAreaJPanel extends javax.swing.JPanel {
     
    JPanel userProcessContainer;
    Network network;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public MaintenanceAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,Network network) {
        initComponents();
        this.network=network;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valuelbl.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userbtn = new javax.swing.JButton();
        manageEmployeebtn = new javax.swing.JButton();
        manageOrganizationbtn = new javax.swing.JButton();
        enterpriselbl = new javax.swing.JLabel();
        valuelbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(76, 89, 115));
        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Maintenance Enterprise Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        userbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userbtn.setText("Manage User");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });
        add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 150, 60));

        manageEmployeebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        manageEmployeebtn.setText("Manage Employee");
        manageEmployeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeebtnActionPerformed(evt);
            }
        });
        add(manageEmployeebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 150, 60));

        manageOrganizationbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        manageOrganizationbtn.setText("Manage Organization");
        manageOrganizationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationbtnActionPerformed(evt);
            }
        });
        add(manageOrganizationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, 60));

        enterpriselbl.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        enterpriselbl.setForeground(new java.awt.Color(255, 255, 255));
        enterpriselbl.setText("Enterprise :");
        add(enterpriselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, 30));

        valuelbl.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        valuelbl.setForeground(new java.awt.Color(255, 255, 255));
        valuelbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(valuelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        // TODO add your handling code here:
        MaintenanceManageUserAccountJPanel muajp = new MaintenanceManageUserAccountJPanel(userProcessContainer, enterprise,network);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userbtnActionPerformed

    private void manageEmployeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeebtnActionPerformed

        MaintenanceManageEmployeeJPanel manageEmployeeJPanel = new MaintenanceManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeebtnActionPerformed

    private void manageOrganizationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationbtnActionPerformed

        MaintenanceManageOrganizationJPanel manageOrganizationJPanel = new MaintenanceManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationbtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriselbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmployeebtn;
    private javax.swing.JButton manageOrganizationbtn;
    private javax.swing.JButton userbtn;
    private javax.swing.JLabel valuelbl;
    // End of variables declaration//GEN-END:variables
    
}
